### ISSUE TITLE
成功部署后，打开网页显示服务器累了，请联系管理员！

### ISSUE THREAD

**Issue by Zombieliu** [YoungWilliamZ/fisco-bcos-browser-docker#6]
部署后打开xxx.5001地址 页面展示 服务器累了，请联系管理员，点其他的什么没啥反应

**Comment by YoungWilliamZ** [comment]
服务端的问题，你可以贴出log吗？

**Comment by jalins** [comment]
@YoungWilliamZ  我也遇到同样的问题了：
![image](https://user-images.githubusercontent.com/31172582/84480942-eb0a1f80-acc7-11ea-9530-f4d00d50bbd2.png)

**Comment by YoungWilliamZ** [comment]
@Jalins JDBC有问题，你看看 db 容器跑起来了吗？

**Comment by jalins** [comment]
> @Jalins JDBC有问题，你看看 db 容器跑起来了吗？

![image](https://user-images.githubusercontent.com/31172582/84481426-a468f500-acc8-11ea-9bdd-7aca6d101599.png)
都起来了

**Comment by YoungWilliamZ** [comment]
@Jalins 请回滚到 39a475cd53f3dc5ffb1a224b62655957bf464b07 试试。上次merge的版本我没测，刚刚测试发现跟你一样，回滚就好了。

```
git reset 39a475cd53f3dc5ffb1a224b62655957bf464b07
docker-compose up -d --build
```

**Comment by jalins** [comment]
> @Jalins 请回滚到 [39a475c](https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/commit/39a475cd53f3dc5ffb1a224b62655957bf464b07) 试试。上次merge的版本我没测，刚刚测试发现跟你一样，回滚就好了。
> 
> ```
> git reset 39a475cd53f3dc5ffb1a224b62655957bf464b07
> docker-compose up -d --build
> ```

回滚之后就变成了 git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git [手动哭脸]

**Comment by YoungWilliamZ** [comment]
> > @Jalins 请回滚到 [39a475c](https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/commit/39a475cd53f3dc5ffb1a224b62655957bf464b07) 试试。上次merge的版本我没测，刚刚测试发现跟你一样，回滚就好了。
> 
> > 
> 
> > ```
> 
> > git reset 39a475cd53f3dc5ffb1a224b62655957bf464b07
> 
> > docker-compose up -d --build
> 
> > ```
> 
> 
> 
> 回滚之后就变成了 git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git [手动哭脸]

那你直接改成gitee试试？替换一下就行了

**Comment by jalins** [comment]
> > > @Jalins 请回滚到 [39a475c](https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/commit/39a475cd53f3dc5ffb1a224b62655957bf464b07) 试试。上次merge的版本我没测，刚刚测试发现跟你一样，回滚就好了。
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > git reset [39a475c](https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/commit/39a475cd53f3dc5ffb1a224b62655957bf464b07)
> > 
> > 
> > > docker-compose up -d --build
> > 
> > 
> > > 
> > 
> > 
> > 回滚之后就变成了 git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git [手动哭脸]
> 
> 那你直接改成gitee试试？替换一下就行了

回滚完好像还是不行，镜像也删除掉重新生成了

**Comment by YoungWilliamZ** [comment]
@Jalins 还是一样的报错吗？

**Comment by jalins** [comment]
> @Jalins 还是一样的报错吗？

是的，跟之前一样的

**Comment by YoungWilliamZ** [comment]
除了github 我全部都换成国内源了，你再试试？

**Comment by daoleno** [comment]
这是因为后端启动的时候，DB还没有初始化好，重启就好了。
