### ISSUE TITLE
一直停留在git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git这一步

### ISSUE THREAD

**Issue by jalins** [YoungWilliamZ/fisco-bcos-browser-docker#7]
Step 7/13 : RUN git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git /fisco-bcos-browser
 ---> Running in b52c2f1df7c3
Cloning into '/fisco-bcos-browser'...
到这一步就一直走不下去，过了很久之后就报错了：
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
ERROR: Service 'fbb_back' failed to build: The command '/bin/sh -c git clone https://github.com/FISCO-BCOS/fisco-bcos-browser.git /fisco-bcos-browser' returned a non-zero code: 128
知道怎么解决吗？

**Comment by YoungWilliamZ** [comment]
网络问题，可以使用代理，或者切换到 [gitee分支](https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/tree/master-gitee)

```
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
```
